config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :test_things
  resources :friends
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/test_thing.rb
class TestThing < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end

end

app/controllers/test_things_controller.rb
class TestThingsController < ApplicationController
  before_action :set_test_thing, only: %i[ show edit update destroy ]

  # GET /test_things or /test_things.json
  def index
    @test_things = TestThing.all
  end

  # GET /test_things/1 or /test_things/1.json
  def show
  end

  # GET /test_things/new
  def new
    @test_thing = TestThing.new
  end

  # GET /test_things/1/edit
  def edit
  end

  # POST /test_things or /test_things.json
  def create
    @test_thing = TestThing.new(test_thing_params)

    respond_to do |format|
      if @test_thing.save
        format.html { redirect_to test_thing_url(@test_thing), notice: "Test thing was successfully created." }
        format.json { render :show, status: :created, location: @test_thing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @test_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_things/1 or /test_things/1.json
  def update
    respond_to do |format|
      if @test_thing.update(test_thing_params)
        format.html { redirect_to test_thing_url(@test_thing), notice: "Test thing was successfully updated." }
        format.json { render :show, status: :ok, location: @test_thing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @test_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_things/1 or /test_things/1.json
  def destroy
    @test_thing.destroy!

    respond_to do |format|
      format.html { redirect_to test_things_url, notice: "Test thing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_thing
      @test_thing = TestThing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def test_thing_params
      params.require(:test_thing).permit(:item_1, :item_2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/test_things_helper.rb
module TestThingsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, html: {class: "needs-validation", novalidate: true}) do |form| %>
  <% if friend.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :first_name, class: "form-control", placeholder:"First name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :last_name, class: "form-control", placeholder:"Last name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :email, class: "form-control", placeholder:"Email" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone, class: "form-control", placeholder:"Phone" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :twitter, class: "form-control", placeholder:"Twitter" %>
  </div>

  <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Edit friend</h1>

<br>

<%= render "form", friend: @friend %>

<div>
  <%= link_to "Profile", @friend, class:"btn btn-secondary" %>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<h1>Friends</h1>

<br>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead class="table-primary">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
        <tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <td><%= link_to 'More', friend, class:"btn btn-primary btn-sm" %></td>
          <td><%= button_to 'Delete', friend, method: :delete, class:"btn btn-danger btn-sm" %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<br>

<div style="max-width: 500px;">
  <%= render "form", friend: @friend %>
</div>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<h1>
  <%= @friend.first_name %>
  <%= @friend.last_name %>
</h1>

<br>

<p class="fs-5"><%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %></p>

<br>

<div>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friends App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "About", home_about_path, class: "nav-link active" %>
        </li>

        <% if not user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link active" %>
        </li>
        <% end %>

        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Friend", new_friend_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-link nav-link active move-2px" %>
        </li>
        <% end %>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About...</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<p>This is my first Ruby on Rails application.</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success" role="alert">
    <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <title>Friends App</title>
  </head>
  <body>
    <%= render "home/header" %>
    <% if notice %>
      <%= render "layouts/alerts" %>
    <% end %>
    <div class="container">
      <br>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/test_things/_form.html.erb
<%= form_with(model: test_thing) do |form| %>
  <% if test_thing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(test_thing.errors.count, "error") %> prohibited this test_thing from being saved:</h2>

      <ul>
        <% test_thing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item_1, style: "display: block" %>
    <%= form.text_field :item_1 %>
  </div>

  <div>
    <%= form.label :item_2, style: "display: block" %>
    <%= form.text_field :item_2 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/test_things/_test_thing.html.erb
<div id="<%= dom_id test_thing %>">
  <p>
    <strong>Item 1:</strong>
    <%= test_thing.item_1 %>
  </p>

  <p>
    <strong>Item 2:</strong>
    <%= test_thing.item_2 %>
  </p>

</div>

app/views/test_things/edit.html.erb
<h1>Editing test thing</h1>

<%= render "form", test_thing: @test_thing %>

<br>

<div>
  <%= link_to "Show this test thing", @test_thing %> |
  <%= link_to "Back to test things", test_things_path %>
</div>

app/views/test_things/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Test things</h1>

<div id="test_things">
  <% @test_things.each do |test_thing| %>
    <%= render test_thing %>
    <p>
      <%= link_to "Show this test thing", test_thing %>
    </p>
  <% end %>
</div>

<%= link_to "New test thing", new_test_thing_path %>

app/views/test_things/new.html.erb
<h1>New test thing</h1>

<%= render "form", test_thing: @test_thing %>

<br>

<div>
  <%= link_to "Back to test things", test_things_path %>
</div>

app/views/test_things/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @test_thing %>

<div>
  <%= link_to "Edit this test thing", edit_test_thing_path(@test_thing) %> |
  <%= link_to "Back to test things", test_things_path %>

  <%= button_to "Destroy this test thing", @test_thing, method: :delete %>
</div>